name: my_portfolio

on: push
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: my_portfolio
        run: npm install

      - name: Build project
        working-directory: my_portfolio
        run: npm run build

      - name: Upload artifacts to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: my_portfolio/dist
  #Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: my_portfolio/dist
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: my_portfolio/dist
